options = optimoptions('ga',...
    'ConstraintTolerance',1e-3,...
    'CreationFcn','gacreationuniform',...
    'MaxGenerations',50,...
    'PlotFcn', @gaplotbestf);
dpmin=ga(@(x) DroneDesign(x),length(dp),[],[],[],[],dprng(1,:),dprng(2,:),[],[6;7;8],options)
